//! Bulk operations for ArticleFeedback entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateArticleFeedbackDto;
use crate::application::service::ArticleFeedbackService;
use crate::domain::entity::ArticleFeedback;

/// Bulk operation handler for ArticleFeedback entities.
///
/// Wraps `ArticleFeedbackService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ArticleFeedbackBulkService = GenericBulkService<ArticleFeedback, CreateArticleFeedbackDto, ArticleFeedbackService>;

// <<< CUSTOM
// END CUSTOM
