//! Bulk operations for ArticleLink entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateArticleLinkDto;
use crate::application::service::ArticleLinkService;
use crate::domain::entity::ArticleLink;

/// Bulk operation handler for ArticleLink entities.
///
/// Wraps `ArticleLinkService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ArticleLinkBulkService = GenericBulkService<ArticleLink, CreateArticleLinkDto, ArticleLinkService>;

// <<< CUSTOM
// END CUSTOM
