//! Bulk operations for ArticleCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateArticleCategoryDto;
use crate::application::service::ArticleCategoryService;
use crate::domain::entity::ArticleCategory;

/// Bulk operation handler for ArticleCategory entities.
///
/// Wraps `ArticleCategoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ArticleCategoryBulkService = GenericBulkService<ArticleCategory, CreateArticleCategoryDto, ArticleCategoryService>;

// <<< CUSTOM
// END CUSTOM
