//! Bulk operations for Article entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateArticleDto;
use crate::application::service::ArticleService;
use crate::domain::entity::Article;

/// Bulk operation handler for Article entities.
///
/// Wraps `ArticleService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ArticleBulkService = GenericBulkService<Article, CreateArticleDto, ArticleService>;

// <<< CUSTOM
// END CUSTOM
