//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod article_category_bulk;
pub mod article_bulk;
pub mod article_link_bulk;
pub mod article_feedback_bulk;

pub use article_category_bulk::ArticleCategoryBulkService;
pub use article_bulk::ArticleBulkService;
pub use article_link_bulk::ArticleLinkBulkService;
pub use article_feedback_bulk::ArticleFeedbackBulkService;

// <<< CUSTOM
// END CUSTOM
