//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification, Specification};

pub mod article_category_specification;
pub mod article_feedback_specification;
pub mod article_link_specification;
pub mod article_specification;

// <<< CUSTOM
// END CUSTOM
