//! Domain policy for ArticleLink aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ArticleLink;

/// Domain policy for ArticleLink — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ArticleLink>` in the `// <<< CUSTOM` zone.
pub type ArticleLinkDomainPolicy = PermitAllPolicy<ArticleLink>;

// <<< CUSTOM
// END CUSTOM
