//! Domain policy for ArticleCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ArticleCategory;

/// Domain policy for ArticleCategory — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ArticleCategory>` in the `// <<< CUSTOM` zone.
pub type ArticleCategoryDomainPolicy = PermitAllPolicy<ArticleCategory>;

// <<< CUSTOM
// END CUSTOM
