//! Application service for ArticleCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `article_category_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateArticleCategoryDto, UpdateArticleCategoryDto};
use crate::domain::entity::ArticleCategory;
use crate::infrastructure::persistence::ArticleCategoryRepository;

/// Application service for ArticleCategory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `article_category_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ArticleCategoryServiceCustom {
///     inner: Arc<ArticleCategoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ArticleCategoryService = GenericCrudService<
    ArticleCategory,
    CreateArticleCategoryDto,
    UpdateArticleCategoryDto,
    ArticleCategoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
