//! Application service for ArticleLink entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `article_link_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateArticleLinkDto, UpdateArticleLinkDto};
use crate::domain::entity::ArticleLink;
use crate::infrastructure::persistence::ArticleLinkRepository;

/// Application service for ArticleLink entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `article_link_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ArticleLinkServiceCustom {
///     inner: Arc<ArticleLinkService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ArticleLinkService = GenericCrudService<
    ArticleLink,
    CreateArticleLinkDto,
    UpdateArticleLinkDto,
    ArticleLinkRepository,
>;

// <<< CUSTOM
// END CUSTOM
