//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod article_category_service;
pub mod article_service;
pub mod article_link_service;
pub mod article_feedback_service;

// <<< CUSTOM
pub mod corpus_write_service;
// END CUSTOM

pub use article_category_service::ArticleCategoryService;
pub use article_service::ArticleService;
pub use article_link_service::ArticleLinkService;
pub use article_feedback_service::ArticleFeedbackService;
// <<< CUSTOM
pub use corpus_write_service::{CorpusWriteService, CorpusError, NewCategory, NewArticle, LinkTarget, ArticleView, ArticleStats};
// END CUSTOM