-- ArticleLink Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the corpus.article_links table.
-- Customize this file to add your initial data.

-- INSERT INTO corpus.article_links (
--     id,
--     company_id,
--     article_id,
--     target_module,
--     target_type,
--     target_id,
--     category_key,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO corpus.article_links (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

