-- ArticleFeedback Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the corpus.article_feedback table.
-- Customize this file to add your initial data.

-- INSERT INTO corpus.article_feedback (
--     id,
--     company_id,
--     article_id,
--     helpful,
--     note,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO corpus.article_feedback (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

