-- Article Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the corpus.articles table.
-- Customize this file to add your initial data.

-- INSERT INTO corpus.articles (
--     id,
--     company_id,
--     category_id,
--     title,
--     body,
--     status,
--     revision,
--     published_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO corpus.articles (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

