-- Migration: Create article_categories table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS corpus;

CREATE TABLE IF NOT EXISTS corpus.article_categories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_article_categories_company_id_code ON corpus.article_categories (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_article_categories_metadata_gin ON corpus.article_categories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_article_categories_metadata_deleted_at ON corpus.article_categories ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_article_categories_metadata_created_at ON corpus.article_categories ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_article_categories_metadata_updated_at ON corpus.article_categories ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corpus.article_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS article_categories_insert_audit ON corpus.article_categories;
CREATE TRIGGER article_categories_insert_audit BEFORE INSERT ON corpus.article_categories
    FOR EACH ROW EXECUTE FUNCTION corpus.article_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS article_categories_update_audit ON corpus.article_categories;
CREATE TRIGGER article_categories_update_audit BEFORE UPDATE ON corpus.article_categories
    FOR EACH ROW EXECUTE FUNCTION corpus.article_categories_audit_timestamp();
