-- Audit Triggers Migration for corpus module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ArticleCategory (corpus.article_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corpus.article_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS article_categories_insert_audit ON corpus.article_categories;
CREATE TRIGGER article_categories_insert_audit BEFORE INSERT ON corpus.article_categories
    FOR EACH ROW EXECUTE FUNCTION corpus.article_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS article_categories_update_audit ON corpus.article_categories;
CREATE TRIGGER article_categories_update_audit BEFORE UPDATE ON corpus.article_categories
    FOR EACH ROW EXECUTE FUNCTION corpus.article_categories_audit_timestamp();

-- ==============================================================================
-- Table: Article (corpus.articles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corpus.articles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS articles_insert_audit ON corpus.articles;
CREATE TRIGGER articles_insert_audit BEFORE INSERT ON corpus.articles
    FOR EACH ROW EXECUTE FUNCTION corpus.articles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS articles_update_audit ON corpus.articles;
CREATE TRIGGER articles_update_audit BEFORE UPDATE ON corpus.articles
    FOR EACH ROW EXECUTE FUNCTION corpus.articles_audit_timestamp();

-- ==============================================================================
-- Table: ArticleLink (corpus.article_links)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corpus.article_links_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS article_links_insert_audit ON corpus.article_links;
CREATE TRIGGER article_links_insert_audit BEFORE INSERT ON corpus.article_links
    FOR EACH ROW EXECUTE FUNCTION corpus.article_links_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS article_links_update_audit ON corpus.article_links;
CREATE TRIGGER article_links_update_audit BEFORE UPDATE ON corpus.article_links
    FOR EACH ROW EXECUTE FUNCTION corpus.article_links_audit_timestamp();

-- ==============================================================================
-- Table: ArticleFeedback (corpus.article_feedback)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION corpus.article_feedback_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS article_feedback_insert_audit ON corpus.article_feedback;
CREATE TRIGGER article_feedback_insert_audit BEFORE INSERT ON corpus.article_feedback
    FOR EACH ROW EXECUTE FUNCTION corpus.article_feedback_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS article_feedback_update_audit ON corpus.article_feedback;
CREATE TRIGGER article_feedback_update_audit BEFORE UPDATE ON corpus.article_feedback
    FOR EACH ROW EXECUTE FUNCTION corpus.article_feedback_audit_timestamp();

