-- Migration: Create articles table
-- Generated by metaphor-schema

-- Create article_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'article_status') THEN
        CREATE TYPE article_status AS ENUM ('draft', 'published', 'archived');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS corpus;

CREATE TABLE IF NOT EXISTS corpus.articles (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    category_id UUID,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    status article_status NOT NULL DEFAULT 'draft',
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 0),
    published_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_articles_company_id_status ON corpus.articles (company_id, status);

CREATE INDEX IF NOT EXISTS idx_articles_category_id ON corpus.articles (category_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_articles_metadata_gin ON corpus.articles USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_articles_metadata_deleted_at ON corpus.articles ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_articles_metadata_created_at ON corpus.articles ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_articles_metadata_updated_at ON corpus.articles ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corpus.articles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS articles_insert_audit ON corpus.articles;
CREATE TRIGGER articles_insert_audit BEFORE INSERT ON corpus.articles
    FOR EACH ROW EXECUTE FUNCTION corpus.articles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS articles_update_audit ON corpus.articles;
CREATE TRIGGER articles_update_audit BEFORE UPDATE ON corpus.articles
    FOR EACH ROW EXECUTE FUNCTION corpus.articles_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE corpus.articles ADD CONSTRAINT fk_articles_category_id FOREIGN KEY (category_id) REFERENCES corpus.article_categories (id);
