-- Company RLS fence for corpus module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for corpus.article_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE corpus.article_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE corpus.article_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_categories_company_isolation ON corpus.article_categories;
CREATE POLICY article_categories_company_isolation ON corpus.article_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for corpus.articles
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE corpus.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE corpus.articles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS articles_company_isolation ON corpus.articles;
CREATE POLICY articles_company_isolation ON corpus.articles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for corpus.article_links
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE corpus.article_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE corpus.article_links FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_links_company_isolation ON corpus.article_links;
CREATE POLICY article_links_company_isolation ON corpus.article_links
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for corpus.article_feedback
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE corpus.article_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE corpus.article_feedback FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_feedback_company_isolation ON corpus.article_feedback;
CREATE POLICY article_feedback_company_isolation ON corpus.article_feedback
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

