-- Enum types for corpus module
-- Generated by metaphor-schema

-- Create article_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'article_status') THEN
        CREATE TYPE article_status AS ENUM ('draft', 'published', 'archived');
    END IF;
END
$$;

