-- Migration: Create article_links table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS corpus;

CREATE TABLE IF NOT EXISTS corpus.article_links (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    article_id UUID NOT NULL,
    target_module TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id UUID NOT NULL,
    category_key TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_article_links_company_id_target_module_target_id ON corpus.article_links (company_id, target_module, target_id);

CREATE INDEX IF NOT EXISTS idx_article_links_company_id_target_module_category_key ON corpus.article_links (company_id, target_module, category_key);

CREATE UNIQUE INDEX IF NOT EXISTS idx_article_links_article_id_target_module_target_id ON corpus.article_links (article_id, target_module, target_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_article_links_metadata_gin ON corpus.article_links USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_article_links_metadata_deleted_at ON corpus.article_links ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_article_links_metadata_created_at ON corpus.article_links ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_article_links_metadata_updated_at ON corpus.article_links ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION corpus.article_links_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS article_links_insert_audit ON corpus.article_links;
CREATE TRIGGER article_links_insert_audit BEFORE INSERT ON corpus.article_links
    FOR EACH ROW EXECUTE FUNCTION corpus.article_links_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS article_links_update_audit ON corpus.article_links;
CREATE TRIGGER article_links_update_audit BEFORE UPDATE ON corpus.article_links
    FOR EACH ROW EXECUTE FUNCTION corpus.article_links_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE corpus.article_links ADD CONSTRAINT fk_article_links_article_id FOREIGN KEY (article_id) REFERENCES corpus.articles (id);
