//! Event handler trait for ArticleLink events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ArticleLinkEvent;

/// Event handler for ArticleLink events.
/// Implement this trait to react to ArticleLink lifecycle events.
pub trait ArticleLinkEventHandler: EventHandler<ArticleLinkEvent> {}
