//! Domain events for ArticleLink entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ArticleLink;

/// Domain events for ArticleLink — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ArticleLink>)` variant.
pub type ArticleLinkEvent = CrudEvent<ArticleLink>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ArticleLink events.
pub type ArticleLinkEventPublisher = Arc<dyn CrudEventPublisher<ArticleLink> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopArticleLinkEventPublisher = NoOpCrudEventPublisher<ArticleLink>;
