//! Domain events for ArticleCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ArticleCategory;

/// Domain events for ArticleCategory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ArticleCategory>)` variant.
pub type ArticleCategoryEvent = CrudEvent<ArticleCategory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ArticleCategory events.
pub type ArticleCategoryEventPublisher = Arc<dyn CrudEventPublisher<ArticleCategory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopArticleCategoryEventPublisher = NoOpCrudEventPublisher<ArticleCategory>;
