//! Domain events for ArticleFeedback entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ArticleFeedback;

/// Domain events for ArticleFeedback — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ArticleFeedback>)` variant.
pub type ArticleFeedbackEvent = CrudEvent<ArticleFeedback>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ArticleFeedback events.
pub type ArticleFeedbackEventPublisher = Arc<dyn CrudEventPublisher<ArticleFeedback> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopArticleFeedbackEventPublisher = NoOpCrudEventPublisher<ArticleFeedback>;
