//! Event handler trait for ArticleFeedback events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ArticleFeedbackEvent;

/// Event handler for ArticleFeedback events.
/// Implement this trait to react to ArticleFeedback lifecycle events.
pub trait ArticleFeedbackEventHandler: EventHandler<ArticleFeedbackEvent> {}
