//! Event handler trait for ArticleCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ArticleCategoryEvent;
use backbone_messaging::EventHandler;

/// Event handler for ArticleCategory events.
/// Implement this trait to react to ArticleCategory lifecycle events.
pub trait ArticleCategoryEventHandler: EventHandler<ArticleCategoryEvent> {}
