//! Event handler trait for Article events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ArticleEvent;
use backbone_messaging::EventHandler;

/// Event handler for Article events.
/// Implement this trait to react to Article lifecycle events.
pub trait ArticleEventHandler: EventHandler<ArticleEvent> {}
