//! Domain events for Article entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Article;

/// Domain events for Article — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Article>)` variant.
pub type ArticleEvent = CrudEvent<Article>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Article events.
pub type ArticleEventPublisher = Arc<dyn CrudEventPublisher<Article> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopArticleEventPublisher = NoOpCrudEventPublisher<Article>;
