//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod article_category_events;
pub mod article_category_event_handlers;
pub mod article_events;
pub mod article_event_handlers;
pub mod article_link_events;
pub mod article_link_event_handlers;
pub mod article_feedback_events;
pub mod article_feedback_event_handlers;

pub use article_category_events::{ArticleCategoryEvent, ArticleCategoryEventPublisher, NoopArticleCategoryEventPublisher};
pub use article_category_event_handlers::ArticleCategoryEventHandler;
pub use article_events::{ArticleEvent, ArticleEventPublisher, NoopArticleEventPublisher};
pub use article_event_handlers::ArticleEventHandler;
pub use article_link_events::{ArticleLinkEvent, ArticleLinkEventPublisher, NoopArticleLinkEventPublisher};
pub use article_link_event_handlers::ArticleLinkEventHandler;
pub use article_feedback_events::{ArticleFeedbackEvent, ArticleFeedbackEventPublisher, NoopArticleFeedbackEventPublisher};
pub use article_feedback_event_handlers::ArticleFeedbackEventHandler;

// <<< CUSTOM
// END CUSTOM
