//! Event subscriber type aliases for Corpus module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::ArticleCategoryEvent;
use crate::domain::event::ArticleEvent;
use crate::domain::event::ArticleLinkEvent;
use crate::domain::event::ArticleFeedbackEvent;

/// Subscriber for ArticleCategory events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ArticleCategoryEventSubscriber = GenericEventSubscriber<ArticleCategoryEvent>;

/// Subscriber for Article events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ArticleEventSubscriber = GenericEventSubscriber<ArticleEvent>;

/// Subscriber for ArticleLink events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ArticleLinkEventSubscriber = GenericEventSubscriber<ArticleLinkEvent>;

/// Subscriber for ArticleFeedback events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ArticleFeedbackEventSubscriber = GenericEventSubscriber<ArticleFeedbackEvent>;

// <<< CUSTOM
// END CUSTOM
