//! ArticleFeedback seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ArticleFeedback data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ARTICLEFEEDBACK SEEDER
// ============================================================================

/// Seeder for article_feedback
pub struct SeedArticleFeedbackSeeder;

impl SeedArticleFeedbackSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedArticleFeedbackSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedArticleFeedbackSeeder {
    fn name(&self) -> &'static str {
        "SeedArticleFeedbackSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corpus.article_feedback table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corpus.article_feedback")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/article_feedback_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corpus.article_feedback")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

