//! ArticleLink seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ArticleLink data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ARTICLELINK SEEDER
// ============================================================================

/// Seeder for article_link
pub struct SeedArticleLinkSeeder;

impl SeedArticleLinkSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedArticleLinkSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedArticleLinkSeeder {
    fn name(&self) -> &'static str {
        "SeedArticleLinkSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corpus.article_links table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corpus.article_links")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/article_link_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corpus.article_links")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

