//! Article seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Article data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ARTICLE SEEDER
// ============================================================================

/// Seeder for article
pub struct SeedArticleSeeder;

impl SeedArticleSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedArticleSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedArticleSeeder {
    fn name(&self) -> &'static str {
        "SeedArticleSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if corpus.articles table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM corpus.articles")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/article_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM corpus.articles")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

