//! Repository trait for Article aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Article aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Article, ArticleStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticlePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ArticlePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ArticlePaginatedResult {
    pub data: Vec<Article>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleFilter {
    pub company_id: Option<Uuid>,
    pub category_id: Option<Uuid>,
    pub title: Option<String>,
    pub body: Option<String>,
    pub status: Option<ArticleStatus>,
}

impl ArticleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.category_id.is_some() || self.title.is_some() || self.body.is_some() || self.status.is_some()
    }
}

/// Repository trait for Article aggregate
///
/// This trait defines the persistence contract for Article entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ArticleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new article entity
    async fn save(&self, entity: &Article) -> Result<Article>;

    /// Find article by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Article>>;

    /// Find all article entities
    async fn find_all(&self) -> Result<Vec<Article>>;

    /// Update article by ID
    async fn update(&self, id: &str, entity: &Article) -> Result<Option<Article>>;

    /// Delete article by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List article with pagination
    async fn list(&self, params: ArticlePaginationParams) -> Result<ArticlePaginatedResult>;

    /// List article with pagination and filters
    async fn list_with_filters(&self, params: ArticlePaginationParams, filters: ArticleFilter) -> Result<ArticlePaginatedResult>;

    /// Count all article entities
    async fn count(&self) -> Result<u64>;

    /// Count article entities matching filters
    async fn count_with_filters(&self, filters: ArticleFilter) -> Result<u64>;

    /// Check if article exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete article by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted article by ID
    async fn restore(&self, id: &str) -> Result<Option<Article>>;

    /// List soft-deleted article entities
    async fn list_deleted(&self, params: ArticlePaginationParams) -> Result<ArticlePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save article entities
    async fn bulk_save(&self, entities: &[Article]) -> Result<Vec<Article>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
