//! Repository trait for ArticleFeedback aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ArticleFeedback aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ArticleFeedback;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleFeedbackPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ArticleFeedbackPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ArticleFeedbackPaginatedResult {
    pub data: Vec<ArticleFeedback>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleFeedbackFilter {
    pub company_id: Option<Uuid>,
    pub article_id: Option<Uuid>,
    pub helpful: Option<bool>,
    pub note: Option<String>,
}

impl ArticleFeedbackFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.article_id.is_some() || self.helpful.is_some() || self.note.is_some()
    }
}

/// Repository trait for ArticleFeedback aggregate
///
/// This trait defines the persistence contract for ArticleFeedback entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ArticleFeedbackRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new article_feedback entity
    async fn save(&self, entity: &ArticleFeedback) -> Result<ArticleFeedback>;

    /// Find article_feedback by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ArticleFeedback>>;

    /// Find all article_feedback entities
    async fn find_all(&self) -> Result<Vec<ArticleFeedback>>;

    /// Update article_feedback by ID
    async fn update(&self, id: &str, entity: &ArticleFeedback) -> Result<Option<ArticleFeedback>>;

    /// Delete article_feedback by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List article_feedback with pagination
    async fn list(&self, params: ArticleFeedbackPaginationParams) -> Result<ArticleFeedbackPaginatedResult>;

    /// List article_feedback with pagination and filters
    async fn list_with_filters(&self, params: ArticleFeedbackPaginationParams, filters: ArticleFeedbackFilter) -> Result<ArticleFeedbackPaginatedResult>;

    /// Count all article_feedback entities
    async fn count(&self) -> Result<u64>;

    /// Count article_feedback entities matching filters
    async fn count_with_filters(&self, filters: ArticleFeedbackFilter) -> Result<u64>;

    /// Check if article_feedback exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete article_feedback by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted article_feedback by ID
    async fn restore(&self, id: &str) -> Result<Option<ArticleFeedback>>;

    /// List soft-deleted article_feedback entities
    async fn list_deleted(&self, params: ArticleFeedbackPaginationParams) -> Result<ArticleFeedbackPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save article_feedback entities
    async fn bulk_save(&self, entities: &[ArticleFeedback]) -> Result<Vec<ArticleFeedback>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
