//! Repository trait for ArticleCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ArticleCategory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ArticleCategory;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleCategoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ArticleCategoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ArticleCategoryPaginatedResult {
    pub data: Vec<ArticleCategory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleCategoryFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
}

impl ArticleCategoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some()
    }
}

/// Repository trait for ArticleCategory aggregate
///
/// This trait defines the persistence contract for ArticleCategory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ArticleCategoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new article_category entity
    async fn save(&self, entity: &ArticleCategory) -> Result<ArticleCategory>;

    /// Find article_category by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ArticleCategory>>;

    /// Find all article_category entities
    async fn find_all(&self) -> Result<Vec<ArticleCategory>>;

    /// Update article_category by ID
    async fn update(&self, id: &str, entity: &ArticleCategory) -> Result<Option<ArticleCategory>>;

    /// Delete article_category by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List article_category with pagination
    async fn list(&self, params: ArticleCategoryPaginationParams) -> Result<ArticleCategoryPaginatedResult>;

    /// List article_category with pagination and filters
    async fn list_with_filters(&self, params: ArticleCategoryPaginationParams, filters: ArticleCategoryFilter) -> Result<ArticleCategoryPaginatedResult>;

    /// Count all article_category entities
    async fn count(&self) -> Result<u64>;

    /// Count article_category entities matching filters
    async fn count_with_filters(&self, filters: ArticleCategoryFilter) -> Result<u64>;

    /// Check if article_category exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete article_category by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted article_category by ID
    async fn restore(&self, id: &str) -> Result<Option<ArticleCategory>>;

    /// List soft-deleted article_category entities
    async fn list_deleted(&self, params: ArticleCategoryPaginationParams) -> Result<ArticleCategoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save article_category entities
    async fn bulk_save(&self, entities: &[ArticleCategory]) -> Result<Vec<ArticleCategory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
