//! Repository trait for ArticleLink aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ArticleLink aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ArticleLink;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleLinkPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ArticleLinkPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ArticleLinkPaginatedResult {
    pub data: Vec<ArticleLink>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ArticleLinkFilter {
    pub company_id: Option<Uuid>,
    pub article_id: Option<Uuid>,
    pub target_module: Option<String>,
    pub target_type: Option<String>,
    pub target_id: Option<Uuid>,
    pub category_key: Option<String>,
}

impl ArticleLinkFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.article_id.is_some() || self.target_module.is_some() || self.target_type.is_some() || self.target_id.is_some() || self.category_key.is_some()
    }
}

/// Repository trait for ArticleLink aggregate
///
/// This trait defines the persistence contract for ArticleLink entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ArticleLinkRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new article_link entity
    async fn save(&self, entity: &ArticleLink) -> Result<ArticleLink>;

    /// Find article_link by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ArticleLink>>;

    /// Find all article_link entities
    async fn find_all(&self) -> Result<Vec<ArticleLink>>;

    /// Update article_link by ID
    async fn update(&self, id: &str, entity: &ArticleLink) -> Result<Option<ArticleLink>>;

    /// Delete article_link by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List article_link with pagination
    async fn list(&self, params: ArticleLinkPaginationParams) -> Result<ArticleLinkPaginatedResult>;

    /// List article_link with pagination and filters
    async fn list_with_filters(&self, params: ArticleLinkPaginationParams, filters: ArticleLinkFilter) -> Result<ArticleLinkPaginatedResult>;

    /// Count all article_link entities
    async fn count(&self) -> Result<u64>;

    /// Count article_link entities matching filters
    async fn count_with_filters(&self, filters: ArticleLinkFilter) -> Result<u64>;

    /// Check if article_link exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete article_link by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted article_link by ID
    async fn restore(&self, id: &str) -> Result<Option<ArticleLink>>;

    /// List soft-deleted article_link entities
    async fn list_deleted(&self, params: ArticleLinkPaginationParams) -> Result<ArticleLinkPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save article_link entities
    async fn bulk_save(&self, entities: &[ArticleLink]) -> Result<Vec<ArticleLink>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
