//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod article_category_repository;
pub mod article_repository;
pub mod article_link_repository;
pub mod article_feedback_repository;

// Re-exports
pub use article_category_repository::{
    ArticleCategoryRepository,
    ArticleCategoryPaginationParams,
    ArticleCategoryPaginatedResult,
    ArticleCategoryFilter,
};
pub use article_repository::{
    ArticleRepository,
    ArticlePaginationParams,
    ArticlePaginatedResult,
    ArticleFilter,
};
pub use article_link_repository::{
    ArticleLinkRepository,
    ArticleLinkPaginationParams,
    ArticleLinkPaginatedResult,
    ArticleLinkFilter,
};
pub use article_feedback_repository::{
    ArticleFeedbackRepository,
    ArticleFeedbackPaginationParams,
    ArticleFeedbackPaginatedResult,
    ArticleFeedbackFilter,
};
