//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod article_category_repository;
pub mod article_feedback_repository;
pub mod article_link_repository;
pub mod article_repository;

// Re-exports
pub use article_category_repository::{
    ArticleCategoryFilter, ArticleCategoryPaginatedResult, ArticleCategoryPaginationParams,
    ArticleCategoryRepository,
};
pub use article_feedback_repository::{
    ArticleFeedbackFilter, ArticleFeedbackPaginatedResult, ArticleFeedbackPaginationParams,
    ArticleFeedbackRepository,
};
pub use article_link_repository::{
    ArticleLinkFilter, ArticleLinkPaginatedResult, ArticleLinkPaginationParams,
    ArticleLinkRepository,
};
pub use article_repository::{
    ArticleFilter, ArticlePaginatedResult, ArticlePaginationParams, ArticleRepository,
};
