//! Repository for Article entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Article SQL — the draft/published/archived transitions and the
//! deflection reads (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Tenancy (ADR-0029): the SQL here carries no tenant key. Writes run through the scoped-execute
//! helper, which rides the request-dedicated connection when the composing service bound one (its
//! fence variables govern what the RLS layer accepts) and falls back to a plain pool execute
//! otherwise. Reads run plainly on the pool the caller names — under a per-unit deployment that is
//! the unit's database, so the pool choice owns isolation.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Article, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::Article;

/// Table name for Article entities
pub const TABLE_NAME: &str = "corpus.articles";

/// Repository for Article entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleRepository(
    backbone_orm::GenericCrudRepository<Article, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleRepository {
    type Target = backbone_orm::GenericCrudRepository<Article, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ArticleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an article authoring writes.
///
/// Mirrors the raw column shape rather than the `Article` entity: `status` is not a parameter at all —
/// a new article is always literal `'draft'::article_status` with `revision` 1, as the original write did.
pub struct NewArticleRow<'a> {
    pub id: Uuid,
    pub category_id: Option<Uuid>,
    pub title: &'a str,
    pub body: &'a str,
}

/// One row of a deflection read — the raw projection a served article is built from.
pub struct ArticleViewRow {
    pub id: Uuid,
    pub title: String,
    pub body: String,
    pub category_id: Option<Uuid>,
}

/// One article's raw feedback tally. The ratio is NOT computed here — the caller derives it, so this
/// stays a pure projection of the columns.
pub struct ArticleStatsRow {
    pub article_id: Uuid,
    pub title: String,
    pub helpful: i64,
    pub not_helpful: i64,
}

fn to_view_row(r: &sqlx::postgres::PgRow) -> ArticleViewRow {
    ArticleViewRow {
        id: r.get("id"),
        title: r.get("title"),
        body: r.get("body"),
        category_id: r.get("category_id"),
    }
}

/// Hand-written Article SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ArticleRepository {
    /// Insert an article. Always lands as a `draft` — the publish gate is the module's invariant.
    ///
    /// Rides the request-dedicated connection when the composing service bound a scope — under a
    /// decorated deployment the fence's WITH CHECK governs the row; with no scope bound this is a
    /// plain insert.
    pub async fn insert_article(
        &self,
        pool: &PgPool,
        a: &NewArticleRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO corpus.articles (id, category_id, title, body, status, revision)
                   VALUES ($1,$2,$3,$4,'draft'::article_status,1)"#,
            )
            .bind(a.id)
            .bind(a.category_id)
            .bind(a.title)
            .bind(a.body),
        )
        .await?;
        Ok(())
    }

    /// Edit an article's content, bumping the revision; returns the NEW revision, or `Ok(None)` when the
    /// article does not exist. A published edit stays published (it is a live fix).
    ///
    /// Rides the request-dedicated connection when the composing service bound a scope (so a deployed
    /// row fence governs the update); plain pool execute otherwise.
    pub async fn update_content(
        &self,
        pool: &PgPool,
        article_id: Uuid,
        title: &str,
        body: &str,
    ) -> Result<Option<i32>, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE corpus.articles SET title=$2, body=$3, revision=revision+1
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL
                   RETURNING revision"#,
            )
            .bind(article_id)
            .bind(title)
            .bind(body),
        )
        .await?;
        Ok(row.map(|r| r.get::<i32, _>("revision")))
    }

    /// The draft→published transition, stamping `published_at`. CAS-gated on `draft` so it happens once;
    /// returns the rows affected so the caller can tell a real transition from a no-op.
    ///
    /// Same scoped-execute contract as [`Self::update_content`].
    pub async fn mark_published(
        &self,
        pool: &PgPool,
        article_id: Uuid,
        published_at: DateTime<Utc>,
    ) -> Result<u64, sqlx::Error> {
        let done = backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE corpus.articles
                   SET status='published'::article_status, published_at=$2
                   WHERE id=$1 AND status='draft'::article_status AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(article_id).bind(published_at),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// The published→archived transition (no longer served, kept for history). CAS-gated on `published`.
    ///
    /// Same scoped-execute contract as [`Self::update_content`].
    pub async fn mark_archived(&self, pool: &PgPool, article_id: Uuid) -> Result<u64, sqlx::Error> {
        let done = backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE corpus.articles SET status='archived'::article_status
                   WHERE id=$1 AND status='published'::article_status AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(article_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// The seam read: the PUBLISHED articles linked to a target, newest first. The `status='published'`
    /// predicate is the publish gate — a draft or archived article must never be served.
    ///
    /// A plain read on the pool the caller names; no scope is bound or invented (ADR-0029).
    pub async fn suggest_for_target(
        &self,
        pool: &PgPool,
        target_module: &str,
        target_id: Uuid,
    ) -> Result<Vec<ArticleViewRow>, sqlx::Error> {
        let rows = sqlx::query(
            r#"SELECT a.id, a.title, a.body, a.category_id
                   FROM corpus.articles a
                   JOIN corpus.article_links l ON l.article_id = a.id
                   WHERE l.target_module = $1 AND l.target_id = $2
                     AND a.status = 'published'::article_status
                     AND (a.metadata->>'deleted_at') IS NULL AND (l.metadata->>'deleted_at') IS NULL
                   ORDER BY a.published_at DESC NULLS LAST"#,
        )
        .bind(target_module)
        .bind(target_id)
        .fetch_all(pool)
        .await?;
        Ok(rows.iter().map(to_view_row).collect())
    }

    /// The browse-by-topic deflection path: PUBLISHED articles for a routing category key. Same publish
    /// gate and same plain-read posture as [`Self::suggest_for_target`].
    pub async fn suggest_for_category(
        &self,
        pool: &PgPool,
        target_module: &str,
        category_key: &str,
    ) -> Result<Vec<ArticleViewRow>, sqlx::Error> {
        let rows = sqlx::query(
            r#"SELECT DISTINCT a.id, a.title, a.body, a.category_id, a.published_at
                   FROM corpus.articles a
                   JOIN corpus.article_links l ON l.article_id = a.id
                   WHERE l.target_module = $1 AND l.category_key = $2
                     AND a.status = 'published'::article_status
                     AND (a.metadata->>'deleted_at') IS NULL AND (l.metadata->>'deleted_at') IS NULL
                   ORDER BY a.published_at DESC NULLS LAST"#,
        )
        .bind(target_module)
        .bind(category_key)
        .fetch_all(pool)
        .await?;
        Ok(rows.iter().map(to_view_row).collect())
    }

    /// Each article's helpful / not-helpful tally — the deflection metric, summed DB-side so a consumer
    /// never re-sums the raw votes. Same plain-read posture as the other reads.
    pub async fn feedback_tallies(
        &self,
        pool: &PgPool,
    ) -> Result<Vec<ArticleStatsRow>, sqlx::Error> {
        let rows = sqlx::query(
            r#"SELECT a.id, a.title,
                          COALESCE(SUM(CASE WHEN f.helpful THEN 1 ELSE 0 END),0) AS helpful,
                          COALESCE(SUM(CASE WHEN NOT f.helpful THEN 1 ELSE 0 END),0) AS not_helpful
                   FROM corpus.articles a
                   LEFT JOIN corpus.article_feedback f
                     ON f.article_id = a.id AND (f.metadata->>'deleted_at') IS NULL
                   WHERE (a.metadata->>'deleted_at') IS NULL
                   GROUP BY a.id, a.title
                   ORDER BY helpful DESC"#,
        )
        .fetch_all(pool)
        .await?;
        Ok(rows
            .iter()
            .map(|r| ArticleStatsRow {
                article_id: r.get("id"),
                title: r.get("title"),
                helpful: r.get("helpful"),
                not_helpful: r.get("not_helpful"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(ArticleRepository, Article, soft_delete);
