//! Repository for ArticleCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ArticleCategory;

/// Table name for ArticleCategory entities
pub const TABLE_NAME: &str = "corpus.article_categories";

/// Repository for ArticleCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleCategoryRepository(
    backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ArticleCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ArticleCategoryRepository, ArticleCategory, soft_delete);
