//! Repository for ArticleLink entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ArticleLink SQL — the idempotent link claim + its conflict re-read
//! (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ArticleLink, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ArticleLink;

/// Table name for ArticleLink entities
pub const TABLE_NAME: &str = "corpus.article_links";

/// Repository for ArticleLink entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleLinkRepository(
    backbone_orm::GenericCrudRepository<ArticleLink, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleLinkRepository {
    type Target = backbone_orm::GenericCrudRepository<ArticleLink, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ArticleLinkRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a link claim writes.
///
/// Mirrors the raw column shape rather than the `ArticleLink` entity — `target_module`/`target_type`
/// are the polymorphic logical FK's discriminators, bound as plain text as the original write did.
pub struct NewLinkRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub article_id: Uuid,
    pub target_module: &'a str,
    pub target_type: &'a str,
    pub target_id: Uuid,
    pub category_key: Option<&'a str>,
}

/// Hand-written ArticleLink SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ArticleLinkRepository {
    /// Claim the (article, target_module, target_id) link slot. `Ok(None)` = this article is already
    /// linked to this target and the caller must re-read the existing link's id, so a re-link is a
    /// true no-op.
    ///
    /// Runs outside a transaction on the pool; the caller wraps it in `with_company_scope(Some(company))`
    /// so the INSERT passes the WITH CHECK fence (ADR-0008).
    pub async fn claim_link(
        &self,
        pool: &PgPool,
        l: &NewLinkRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"INSERT INTO corpus.article_links
                     (id, company_id, article_id, target_module, target_type, target_id, category_key)
                   VALUES ($1,$2,$3,$4,$5,$6,$7)
                   ON CONFLICT (article_id, target_module, target_id) WHERE (metadata->>'deleted_at') IS NULL
                   DO NOTHING
                   RETURNING id"#,
            )
            .bind(l.id).bind(l.company_id).bind(l.article_id).bind(l.target_module).bind(l.target_type)
            .bind(l.target_id).bind(l.category_key),
        )
        .await
    }

    /// Re-read the existing link's id after a losing claim. Caller supplies the company scope, as above.
    pub async fn fetch_link_id(
        &self,
        pool: &PgPool,
        article_id: Uuid,
        target_module: &str,
        target_id: Uuid,
    ) -> Result<Uuid, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM corpus.article_links
                   WHERE article_id=$1 AND target_module=$2 AND target_id=$3 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(article_id).bind(target_module).bind(target_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(ArticleLinkRepository, ArticleLink, soft_delete);
