//! Repository for ArticleFeedback entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ArticleFeedback;

/// Table name for ArticleFeedback entities
pub const TABLE_NAME: &str = "corpus.article_feedback";

/// Repository for ArticleFeedback entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleFeedbackRepository(
    backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleFeedbackRepository {
    type Target = backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ArticleFeedbackRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ArticleFeedbackRepository, ArticleFeedback, soft_delete);
