//! Repository for ArticleFeedback entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ArticleFeedback SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Tenancy (ADR-0029): the SQL here carries no tenant key. The scoped-execute helper rides the
//! request-dedicated connection when the composing service bound one (its fence variables govern
//! what the RLS layer accepts) and falls back to a plain pool execute otherwise.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::ArticleFeedback;

/// Table name for ArticleFeedback entities
pub const TABLE_NAME: &str = "corpus.article_feedback";

/// Repository for ArticleFeedback entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleFeedbackRepository(
    backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleFeedbackRepository {
    type Target = backbone_orm::GenericCrudRepository<ArticleFeedback, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ArticleFeedbackRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a "was this helpful?" vote writes.
///
/// Mirrors the raw column shape rather than the `ArticleFeedback` entity.
pub struct NewFeedbackRow<'a> {
    pub id: Uuid,
    pub article_id: Uuid,
    pub helpful: bool,
    pub note: Option<&'a str>,
}

/// Hand-written ArticleFeedback SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl ArticleFeedbackRepository {
    /// Record a reader's vote — the raw input behind the deflection metric.
    ///
    /// Rides the request-dedicated connection when the composing service bound a scope — under a
    /// decorated deployment the fence's WITH CHECK governs the row; with no scope bound this is a
    /// plain insert.
    pub async fn insert_feedback(
        &self,
        pool: &PgPool,
        f: &NewFeedbackRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                "INSERT INTO corpus.article_feedback (id, article_id, helpful, note) VALUES ($1,$2,$3,$4)")
                .bind(f.id).bind(f.article_id).bind(f.helpful).bind(f.note),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(ArticleFeedbackRepository, ArticleFeedback, soft_delete);
