//! Repository for ArticleCategory entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ArticleCategory SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ArticleCategory;

/// Table name for ArticleCategory entities
pub const TABLE_NAME: &str = "corpus.article_categories";

/// Repository for ArticleCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ArticleCategoryRepository(
    backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ArticleCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<ArticleCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ArticleCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a category creation writes.
///
/// Mirrors the raw column shape rather than the `ArticleCategory` entity.
pub struct NewCategoryRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
}

/// Hand-written ArticleCategory SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl ArticleCategoryRepository {
    /// Insert a category.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_category(
        &self,
        pool: &PgPool,
        c: &NewCategoryRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                "INSERT INTO corpus.article_categories (id, company_id, code, name) VALUES ($1,$2,$3,$4)")
                .bind(c.id).bind(c.company_id).bind(c.code).bind(c.name),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(ArticleCategoryRepository, ArticleCategory, soft_delete);
