//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod article_category_repository;
mod article_repository;
mod article_link_repository;
mod article_feedback_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use article_category_repository::ArticleCategoryRepository;
pub use article_repository::ArticleRepository;
pub use article_link_repository::ArticleLinkRepository;
pub use article_feedback_repository::ArticleFeedbackRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
