//! Validator for Article entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Article>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::Article;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};
use backbone_core::{NonNegative, RequiredString};

/// Validator type alias for Article entities.
pub type ArticleValidator = EntityValidator<Article>;

/// Build a validator for Article with all schema-defined field rules.
pub fn article_validator() -> ArticleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Article| &e.title))
        .rule(RequiredString::new("body", |e: &Article| &e.body))
        .rule(NonNegative::new("revision", |e: &Article| {
            e.revision as i64
        }))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
