//! Validator for ArticleCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ArticleCategory>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ArticleCategory;

/// Validator type alias for ArticleCategory entities.
pub type ArticleCategoryValidator = EntityValidator<ArticleCategory>;

/// Build a validator for ArticleCategory with all schema-defined field rules.
pub fn article_category_validator() -> ArticleCategoryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &ArticleCategory| &e.code))
        .rule(RequiredString::new("name", |e: &ArticleCategory| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
