//! Validator for ArticleLink entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ArticleLink>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ArticleLink;

/// Validator type alias for ArticleLink entities.
pub type ArticleLinkValidator = EntityValidator<ArticleLink>;

/// Build a validator for ArticleLink with all schema-defined field rules.
pub fn article_link_validator() -> ArticleLinkValidator {
    EntityValidator::new()
        .rule(RequiredString::new("target_module", |e: &ArticleLink| &e.target_module))
        .rule(RequiredString::new("target_type", |e: &ArticleLink| &e.target_type))
        .rule(OptionalNotBlank::new("category_key", |e: &ArticleLink| e.category_key.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
