//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod article_category_validator;
pub mod article_validator;
pub mod article_link_validator;
pub mod article_feedback_validator;

pub use article_category_validator::{ArticleCategoryValidator, article_category_validator};
pub use article_validator::{ArticleValidator, article_validator};
pub use article_link_validator::{ArticleLinkValidator, article_link_validator};
pub use article_feedback_validator::{ArticleFeedbackValidator, article_feedback_validator};

// <<< CUSTOM
// END CUSTOM
