//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{EntityValidator, ValidationError, ValidationErrors, ValidationResult};

pub mod article_category_validator;
pub mod article_feedback_validator;
pub mod article_link_validator;
pub mod article_validator;

pub use article_category_validator::{article_category_validator, ArticleCategoryValidator};
pub use article_feedback_validator::{article_feedback_validator, ArticleFeedbackValidator};
pub use article_link_validator::{article_link_validator, ArticleLinkValidator};
pub use article_validator::{article_validator, ArticleValidator};

// <<< CUSTOM
// END CUSTOM
