//! Auth configuration for ArticleFeedback handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ArticleFeedback>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ArticleFeedbackService;
use crate::domain::entity::ArticleFeedback;

/// Permission string constants for ArticleFeedback operations.
pub mod permissions {
    pub const LIST:        &str = "article_feedback:list";
    pub const READ:        &str = "article_feedback:read";
    pub const CREATE:      &str = "article_feedback:create";
    pub const UPDATE:      &str = "article_feedback:update";
    pub const DELETE:      &str = "article_feedback:delete";
    pub const RESTORE:     &str = "article_feedback:restore";
    pub const TRASH:       &str = "article_feedback:trash";
    pub const EMPTY_TRASH: &str = "article_feedback:empty_trash";
    pub const BULK_CREATE: &str = "article_feedback:bulk_create";
    pub const UPSERT:      &str = "article_feedback:upsert";
}

/// Resource policy for ArticleFeedback — maps CRUD actions to permission strings.
pub struct ArticleFeedbackPolicy;

#[async_trait]
impl ResourcePolicy<ArticleFeedback> for ArticleFeedbackPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ArticleFeedback,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ArticleFeedback handlers.
///
/// Wraps `ArticleFeedbackService` and checks `ArticleFeedbackPolicy` before delegating.
pub type ArticleFeedbackGuard = PermissionGuard<ArticleFeedback>;

/// Service-integrated permission guard for ArticleFeedback (for use in generated handlers).
pub type ArticleFeedbackServiceGuard = ServicePermissionGuard<ArticleFeedback, ArticleFeedbackService, ArticleFeedbackPolicy>;

// <<< CUSTOM
// END CUSTOM
