//! Auth configuration for Article handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Article>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ArticleService;
use crate::domain::entity::Article;

/// Permission string constants for Article operations.
pub mod permissions {
    pub const LIST:        &str = "article:list";
    pub const READ:        &str = "article:read";
    pub const CREATE:      &str = "article:create";
    pub const UPDATE:      &str = "article:update";
    pub const DELETE:      &str = "article:delete";
    pub const RESTORE:     &str = "article:restore";
    pub const TRASH:       &str = "article:trash";
    pub const EMPTY_TRASH: &str = "article:empty_trash";
    pub const BULK_CREATE: &str = "article:bulk_create";
    pub const UPSERT:      &str = "article:upsert";
}

/// Resource policy for Article — maps CRUD actions to permission strings.
pub struct ArticlePolicy;

#[async_trait]
impl ResourcePolicy<Article> for ArticlePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Article,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Article handlers.
///
/// Wraps `ArticleService` and checks `ArticlePolicy` before delegating.
pub type ArticleGuard = PermissionGuard<Article>;

/// Service-integrated permission guard for Article (for use in generated handlers).
pub type ArticleServiceGuard = ServicePermissionGuard<Article, ArticleService, ArticlePolicy>;

// <<< CUSTOM
// END CUSTOM
