//! Auth configuration for ArticleCategory handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ArticleCategory>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ArticleCategoryService;
use crate::domain::entity::ArticleCategory;

/// Permission string constants for ArticleCategory operations.
pub mod permissions {
    pub const LIST:        &str = "article_category:list";
    pub const READ:        &str = "article_category:read";
    pub const CREATE:      &str = "article_category:create";
    pub const UPDATE:      &str = "article_category:update";
    pub const DELETE:      &str = "article_category:delete";
    pub const RESTORE:     &str = "article_category:restore";
    pub const TRASH:       &str = "article_category:trash";
    pub const EMPTY_TRASH: &str = "article_category:empty_trash";
    pub const BULK_CREATE: &str = "article_category:bulk_create";
    pub const UPSERT:      &str = "article_category:upsert";
}

/// Resource policy for ArticleCategory — maps CRUD actions to permission strings.
pub struct ArticleCategoryPolicy;

#[async_trait]
impl ResourcePolicy<ArticleCategory> for ArticleCategoryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ArticleCategory,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ArticleCategory handlers.
///
/// Wraps `ArticleCategoryService` and checks `ArticleCategoryPolicy` before delegating.
pub type ArticleCategoryGuard = PermissionGuard<ArticleCategory>;

/// Service-integrated permission guard for ArticleCategory (for use in generated handlers).
pub type ArticleCategoryServiceGuard = ServicePermissionGuard<ArticleCategory, ArticleCategoryService, ArticleCategoryPolicy>;

// <<< CUSTOM
// END CUSTOM
