//! Auth configuration for ArticleLink handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ArticleLink>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ArticleLinkService;
use crate::domain::entity::ArticleLink;

/// Permission string constants for ArticleLink operations.
pub mod permissions {
    pub const LIST:        &str = "article_link:list";
    pub const READ:        &str = "article_link:read";
    pub const CREATE:      &str = "article_link:create";
    pub const UPDATE:      &str = "article_link:update";
    pub const DELETE:      &str = "article_link:delete";
    pub const RESTORE:     &str = "article_link:restore";
    pub const TRASH:       &str = "article_link:trash";
    pub const EMPTY_TRASH: &str = "article_link:empty_trash";
    pub const BULK_CREATE: &str = "article_link:bulk_create";
    pub const UPSERT:      &str = "article_link:upsert";
}

/// Resource policy for ArticleLink — maps CRUD actions to permission strings.
pub struct ArticleLinkPolicy;

#[async_trait]
impl ResourcePolicy<ArticleLink> for ArticleLinkPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ArticleLink,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ArticleLink handlers.
///
/// Wraps `ArticleLinkService` and checks `ArticleLinkPolicy` before delegating.
pub type ArticleLinkGuard = PermissionGuard<ArticleLink>;

/// Service-integrated permission guard for ArticleLink (for use in generated handlers).
pub type ArticleLinkServiceGuard = ServicePermissionGuard<ArticleLink, ArticleLinkService, ArticleLinkPolicy>;

// <<< CUSTOM
// END CUSTOM
