//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod article_category_auth;
pub mod article_auth;
pub mod article_link_auth;
pub mod article_feedback_auth;

pub use article_category_auth::{ArticleCategoryPolicy, ArticleCategoryGuard, ArticleCategoryServiceGuard};
pub use article_auth::{ArticlePolicy, ArticleGuard, ArticleServiceGuard};
pub use article_link_auth::{ArticleLinkPolicy, ArticleLinkGuard, ArticleLinkServiceGuard};
pub use article_feedback_auth::{ArticleFeedbackPolicy, ArticleFeedbackGuard, ArticleFeedbackServiceGuard};

// <<< CUSTOM
// END CUSTOM
