//! ArticleLink API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ArticleLink CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ARTICLELINK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ArticleLink
pub struct ArticleLinkTestData;

impl TestDataGenerator for ArticleLinkTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "article_id": Uuid::new_v4().to_string(),
            "target_module": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "target_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "target_id": Uuid::new_v4().to_string(),
            "category_key": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "article_id": Uuid::new_v4().to_string(),
            "target_module": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "target_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "target_id": Uuid::new_v4().to_string(),
            "category_key": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/articles", &super::article_api_test::ArticleTestData).await {
            deps.push(("article_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ARTICLELINK API TEST
// ============================================================================

/// ArticleLink API test suite
pub struct ArticleLinkApiTest {
    inner: GenericCrudTest<ArticleLinkTestData>,
}

impl ArticleLinkApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/article_links", "ArticleLink");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ArticleLinkTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ArticleLinkApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_article_link_crud() {
        let mut test = ArticleLinkApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ArticleLink specific tests here
// <<< CUSTOM TESTS END >>>
