//! Article API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Article CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ARTICLE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Article
pub struct ArticleTestData;

impl TestDataGenerator for ArticleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "category_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "draft",
            "revision": 1,
            "published_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "category_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "draft",
            "revision": 1,
            "published_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ARTICLE API TEST
// ============================================================================

/// Article API test suite
pub struct ArticleApiTest {
    inner: GenericCrudTest<ArticleTestData>,
}

impl ArticleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/articles", "Article");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ArticleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ArticleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_article_crud() {
        let mut test = ArticleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Article specific tests here
// <<< CUSTOM TESTS END >>>
