//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod article_category_api_test;
pub mod article_api_test;
pub mod article_link_api_test;
pub mod article_feedback_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use article_category_api_test::*;
pub use article_api_test::*;
pub use article_link_api_test::*;
pub use article_feedback_api_test::*;
