//! Corpus Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ArticleCategoryService;
use crate::application::service::ArticleService;
use crate::application::service::ArticleLinkService;
use crate::application::service::ArticleFeedbackService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ArticleCategory service
    pub article_category_service: Arc<ArticleCategoryService>,
    /// Article service
    pub article_service: Arc<ArticleService>,
    /// ArticleLink service
    pub article_link_service: Arc<ArticleLinkService>,
    /// ArticleFeedback service
    pub article_feedback_service: Arc<ArticleFeedbackService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        article_category_service: Arc<ArticleCategoryService>,
        article_service: Arc<ArticleService>,
        article_link_service: Arc<ArticleLinkService>,
        article_feedback_service: Arc<ArticleFeedbackService>
    ) -> Self {
        Self {
            article_category_service,
            article_service,
            article_link_service,
            article_feedback_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::CorpusModule) -> Self {
        Self {
            article_category_service: module.article_category_service.clone(),
            article_service: module.article_service.clone(),
            article_link_service: module.article_link_service.clone(),
            article_feedback_service: module.article_feedback_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    article_category_service: Option<Arc<ArticleCategoryService>>,
    article_service: Option<Arc<ArticleService>>,
    article_link_service: Option<Arc<ArticleLinkService>>,
    article_feedback_service: Option<Arc<ArticleFeedbackService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ArticleCategory service.
    pub fn with_article_category_service(mut self, service: Arc<ArticleCategoryService>) -> Self {
        self.article_category_service = Some(service);
        self
    }

    /// Set the Article service.
    pub fn with_article_service(mut self, service: Arc<ArticleService>) -> Self {
        self.article_service = Some(service);
        self
    }

    /// Set the ArticleLink service.
    pub fn with_article_link_service(mut self, service: Arc<ArticleLinkService>) -> Self {
        self.article_link_service = Some(service);
        self
    }

    /// Set the ArticleFeedback service.
    pub fn with_article_feedback_service(mut self, service: Arc<ArticleFeedbackService>) -> Self {
        self.article_feedback_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            article_category_service: self.article_category_service.expect("article_category_service is required"),
            article_service: self.article_service.expect("article_service is required"),
            article_link_service: self.article_link_service.expect("article_link_service is required"),
            article_feedback_service: self.article_feedback_service.expect("article_feedback_service is required"),
        }
    }
}
