//! Public events for Corpus module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ARTICLECATEGORY EVENTS
// ============================================================================

/// Event published when a ArticleCategory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategoryCreatedEvent {
    pub id: ArticleCategoryId,
    pub data: ArticleCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleCategory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategoryUpdatedEvent {
    pub id: ArticleCategoryId,
    pub data: ArticleCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleCategory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategoryDeletedEvent {
    pub id: ArticleCategoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ARTICLE EVENTS
// ============================================================================

/// Event published when a Article is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCreatedEvent {
    pub id: ArticleId,
    pub data: ArticleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Article is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleUpdatedEvent {
    pub id: ArticleId,
    pub data: ArticleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Article is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleDeletedEvent {
    pub id: ArticleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ARTICLELINK EVENTS
// ============================================================================

/// Event published when a ArticleLink is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkCreatedEvent {
    pub id: ArticleLinkId,
    pub data: ArticleLinkDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleLink is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkUpdatedEvent {
    pub id: ArticleLinkId,
    pub data: ArticleLinkDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleLink is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkDeletedEvent {
    pub id: ArticleLinkId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ARTICLEFEEDBACK EVENTS
// ============================================================================

/// Event published when a ArticleFeedback is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackCreatedEvent {
    pub id: ArticleFeedbackId,
    pub data: ArticleFeedbackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleFeedback is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackUpdatedEvent {
    pub id: ArticleFeedbackId,
    pub data: ArticleFeedbackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ArticleFeedback is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackDeletedEvent {
    pub id: ArticleFeedbackId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Corpus module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CorpusEvent {
    ArticleCategoryCreated(ArticleCategoryCreatedEvent),
    ArticleCategoryUpdated(ArticleCategoryUpdatedEvent),
    ArticleCategoryDeleted(ArticleCategoryDeletedEvent),
    ArticleCreated(ArticleCreatedEvent),
    ArticleUpdated(ArticleUpdatedEvent),
    ArticleDeleted(ArticleDeletedEvent),
    ArticleLinkCreated(ArticleLinkCreatedEvent),
    ArticleLinkUpdated(ArticleLinkUpdatedEvent),
    ArticleLinkDeleted(ArticleLinkDeletedEvent),
    ArticleFeedbackCreated(ArticleFeedbackCreatedEvent),
    ArticleFeedbackUpdated(ArticleFeedbackUpdatedEvent),
    ArticleFeedbackDeleted(ArticleFeedbackDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorpusEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for CorpusEventMetadata {
    fn default() -> Self {
        Self {
            module: "corpus",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
