//! Corpus Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Corpus exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use corpus::exports::{ArticleCategoryDto, CorpusQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ArticleCategoryDto` - Data transfer object for ArticleCategory
/// - `ArticleCategorySummary` - Summary view of ArticleCategory
/// - `ArticleCategoryId` - Type-safe ID wrapper
/// - `ArticleDto` - Data transfer object for Article
/// - `ArticleSummary` - Summary view of Article
/// - `ArticleId` - Type-safe ID wrapper
/// - `ArticleLinkDto` - Data transfer object for ArticleLink
/// - `ArticleLinkSummary` - Summary view of ArticleLink
/// - `ArticleLinkId` - Type-safe ID wrapper
/// - `ArticleFeedbackDto` - Data transfer object for ArticleFeedback
/// - `ArticleFeedbackSummary` - Summary view of ArticleFeedback
/// - `ArticleFeedbackId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `CorpusQueryService` - Read-only queries
///
/// ## Public Events
/// - `ArticleCategoryCreatedEvent` - Published when ArticleCategory is created
/// - `ArticleCategoryUpdatedEvent` - Published when ArticleCategory is updated
/// - `ArticleCategoryDeletedEvent` - Published when ArticleCategory is deleted
/// - `ArticleCreatedEvent` - Published when Article is created
/// - `ArticleUpdatedEvent` - Published when Article is updated
/// - `ArticleDeletedEvent` - Published when Article is deleted
/// - `ArticleLinkCreatedEvent` - Published when ArticleLink is created
/// - `ArticleLinkUpdatedEvent` - Published when ArticleLink is updated
/// - `ArticleLinkDeletedEvent` - Published when ArticleLink is deleted
/// - `ArticleFeedbackCreatedEvent` - Published when ArticleFeedback is created
/// - `ArticleFeedbackUpdatedEvent` - Published when ArticleFeedback is updated
/// - `ArticleFeedbackDeletedEvent` - Published when ArticleFeedback is deleted
pub struct ExportSummary;
