//! Public services for Corpus module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Corpus module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait CorpusQueryService: Send + Sync {
    /// Get ArticleCategory by ID
    async fn get_article_category(&self, id: ArticleCategoryId) -> Result<Option<ArticleCategoryDto>>;

    /// Get ArticleCategory summary by ID
    async fn get_article_category_summary(&self, id: ArticleCategoryId) -> Result<Option<ArticleCategorySummary>>;

    /// Check if ArticleCategory exists
    async fn article_category_exists(&self, id: ArticleCategoryId) -> Result<bool>;

    /// Get Article by ID
    async fn get_article(&self, id: ArticleId) -> Result<Option<ArticleDto>>;

    /// Get Article summary by ID
    async fn get_article_summary(&self, id: ArticleId) -> Result<Option<ArticleSummary>>;

    /// Check if Article exists
    async fn article_exists(&self, id: ArticleId) -> Result<bool>;

    /// Get ArticleLink by ID
    async fn get_article_link(&self, id: ArticleLinkId) -> Result<Option<ArticleLinkDto>>;

    /// Get ArticleLink summary by ID
    async fn get_article_link_summary(&self, id: ArticleLinkId) -> Result<Option<ArticleLinkSummary>>;

    /// Check if ArticleLink exists
    async fn article_link_exists(&self, id: ArticleLinkId) -> Result<bool>;

    /// Get ArticleFeedback by ID
    async fn get_article_feedback(&self, id: ArticleFeedbackId) -> Result<Option<ArticleFeedbackDto>>;

    /// Get ArticleFeedback summary by ID
    async fn get_article_feedback_summary(&self, id: ArticleFeedbackId) -> Result<Option<ArticleFeedbackSummary>>;

    /// Check if ArticleFeedback exists
    async fn article_feedback_exists(&self, id: ArticleFeedbackId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of CorpusQueryService
pub struct CorpusQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> CorpusQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
