//! Public types for Corpus module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// ARTICLECATEGORY TYPES
// ============================================================================

/// Type-safe ID for ArticleCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ArticleCategoryId(pub Uuid);

impl ArticleCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ArticleCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ArticleCategoryId> for Uuid {
    fn from(id: ArticleCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for ArticleCategory
///
/// This is the public representation of ArticleCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategoryDto {
    pub id: ArticleCategoryId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub metadata: serde_json::Value,
}

/// Summary view of ArticleCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategorySummary {
    pub id: ArticleCategoryId,
    pub name: String,
}

/// Reference to ArticleCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleCategoryRef {
    pub id: ArticleCategoryId,
}

// ============================================================================
// ARTICLE TYPES
// ============================================================================

/// Type-safe ID for Article
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ArticleId(pub Uuid);

impl ArticleId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ArticleId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ArticleId> for Uuid {
    fn from(id: ArticleId) -> Self {
        id.0
    }
}

/// Data transfer object for Article
///
/// This is the public representation of Article for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleDto {
    pub id: ArticleId,
    pub company_id: Uuid,
    pub category_id: Option<Uuid>,
    pub title: String,
    pub body: String,
    pub status: ArticleStatus,
    pub revision: i32,
    pub published_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Article for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleSummary {
    pub id: ArticleId,
    pub title: String,
    pub status: ArticleStatus,
}

/// Reference to Article for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleRef {
    pub id: ArticleId,
}

// ============================================================================
// ARTICLELINK TYPES
// ============================================================================

/// Type-safe ID for ArticleLink
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ArticleLinkId(pub Uuid);

impl ArticleLinkId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ArticleLinkId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ArticleLinkId> for Uuid {
    fn from(id: ArticleLinkId) -> Self {
        id.0
    }
}

/// Data transfer object for ArticleLink
///
/// This is the public representation of ArticleLink for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkDto {
    pub id: ArticleLinkId,
    pub company_id: Uuid,
    pub article_id: Uuid,
    pub target_module: String,
    pub target_type: String,
    pub target_id: Uuid,
    pub category_key: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of ArticleLink for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkSummary {
    pub id: ArticleLinkId,
}

/// Reference to ArticleLink for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleLinkRef {
    pub id: ArticleLinkId,
}

// ============================================================================
// ARTICLEFEEDBACK TYPES
// ============================================================================

/// Type-safe ID for ArticleFeedback
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ArticleFeedbackId(pub Uuid);

impl ArticleFeedbackId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ArticleFeedbackId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ArticleFeedbackId> for Uuid {
    fn from(id: ArticleFeedbackId) -> Self {
        id.0
    }
}

/// Data transfer object for ArticleFeedback
///
/// This is the public representation of ArticleFeedback for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackDto {
    pub id: ArticleFeedbackId,
    pub company_id: Uuid,
    pub article_id: Uuid,
    pub helpful: bool,
    pub note: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of ArticleFeedback for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackSummary {
    pub id: ArticleFeedbackId,
}

/// Reference to ArticleFeedback for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleFeedbackRef {
    pub id: ArticleFeedbackId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
