//! Corpus Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ArticleCategoryService;
pub use application::service::ArticleService;
pub use application::service::ArticleLinkService;
pub use application::service::ArticleFeedbackService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Corpus module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let corpus = CorpusModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = corpus.all_crud_routes();
/// ```
pub struct CorpusModule {
    pub article_category_service: Arc<ArticleCategoryService>,
    pub article_service: Arc<ArticleService>,
    pub article_link_service: Arc<ArticleLinkService>,
    pub article_feedback_service: Arc<ArticleFeedbackService>,
}

impl CorpusModule {
    /// Create a new module builder
    pub fn builder() -> CorpusModuleBuilder {
        CorpusModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_article_category_routes,
            create_article_routes,
            create_article_link_routes,
            create_article_feedback_routes,
        };

        Router::new()
            .merge(create_article_category_routes(self.article_category_service.clone()))
            .merge(create_article_routes(self.article_service.clone()))
            .merge(create_article_link_routes(self.article_link_service.clone()))
            .merge(create_article_feedback_routes(self.article_feedback_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for CorpusModule
pub struct CorpusModuleBuilder {
    db_pool: Option<PgPool>,
}

impl CorpusModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<CorpusModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // ArticleCategory service
        let article_category_repository = Arc::new(ArticleCategoryRepository::new(db_pool.clone()));
        let article_category_service = Arc::new(ArticleCategoryService::with_repository(article_category_repository.clone()));

        // Article service
        let article_repository = Arc::new(ArticleRepository::new(db_pool.clone()));
        let article_service = Arc::new(ArticleService::with_repository(article_repository.clone()));

        // ArticleLink service
        let article_link_repository = Arc::new(ArticleLinkRepository::new(db_pool.clone()));
        let article_link_service = Arc::new(ArticleLinkService::with_repository(article_link_repository.clone()));

        // ArticleFeedback service
        let article_feedback_repository = Arc::new(ArticleFeedbackRepository::new(db_pool.clone()));
        let article_feedback_service = Arc::new(ArticleFeedbackService::with_repository(article_feedback_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(CorpusModule {
            article_category_service,
            article_service,
            article_link_service,
            article_feedback_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for CorpusModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
