//! Use case type aliases for ArticleFeedback aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateArticleFeedbackDto, UpdateArticleFeedbackDto};
use crate::application::service::ArticleFeedbackService;
use crate::domain::entity::ArticleFeedback;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateArticleFeedbackUseCase = CreateUseCase<ArticleFeedback, CreateArticleFeedbackDto, ArticleFeedbackService>;
pub type UpdateArticleFeedbackUseCase = UpdateUseCase<ArticleFeedback, UpdateArticleFeedbackDto, ArticleFeedbackService>;
pub type GetArticleFeedbackUseCase    = GetUseCase<ArticleFeedback, ArticleFeedbackService>;
pub type DeleteArticleFeedbackUseCase = DeleteUseCase<ArticleFeedback, ArticleFeedbackService>;
pub type ListArticleFeedbackUseCase   = ListUseCase<ArticleFeedback, ArticleFeedbackService>;

// <<< CUSTOM
// END CUSTOM
