//! Use case type aliases for ArticleCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateArticleCategoryDto, UpdateArticleCategoryDto};
use crate::application::service::ArticleCategoryService;
use crate::domain::entity::ArticleCategory;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateArticleCategoryUseCase = CreateUseCase<ArticleCategory, CreateArticleCategoryDto, ArticleCategoryService>;
pub type UpdateArticleCategoryUseCase = UpdateUseCase<ArticleCategory, UpdateArticleCategoryDto, ArticleCategoryService>;
pub type GetArticleCategoryUseCase    = GetUseCase<ArticleCategory, ArticleCategoryService>;
pub type DeleteArticleCategoryUseCase = DeleteUseCase<ArticleCategory, ArticleCategoryService>;
pub type ListArticleCategoryUseCase   = ListUseCase<ArticleCategory, ArticleCategoryService>;

// <<< CUSTOM
// END CUSTOM
