//! Use case type aliases for Article aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateArticleDto, UpdateArticleDto};
use crate::application::service::ArticleService;
use crate::domain::entity::Article;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateArticleUseCase = CreateUseCase<Article, CreateArticleDto, ArticleService>;
pub type UpdateArticleUseCase = UpdateUseCase<Article, UpdateArticleDto, ArticleService>;
pub type GetArticleUseCase    = GetUseCase<Article, ArticleService>;
pub type DeleteArticleUseCase = DeleteUseCase<Article, ArticleService>;
pub type ListArticleUseCase   = ListUseCase<Article, ArticleService>;

// <<< CUSTOM
// END CUSTOM
