//! Use case type aliases for ArticleLink aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateArticleLinkDto, UpdateArticleLinkDto};
use crate::application::service::ArticleLinkService;
use crate::domain::entity::ArticleLink;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateArticleLinkUseCase = CreateUseCase<ArticleLink, CreateArticleLinkDto, ArticleLinkService>;
pub type UpdateArticleLinkUseCase = UpdateUseCase<ArticleLink, UpdateArticleLinkDto, ArticleLinkService>;
pub type GetArticleLinkUseCase    = GetUseCase<ArticleLink, ArticleLinkService>;
pub type DeleteArticleLinkUseCase = DeleteUseCase<ArticleLink, ArticleLinkService>;
pub type ListArticleLinkUseCase   = ListUseCase<ArticleLink, ArticleLinkService>;

// <<< CUSTOM
// END CUSTOM
