//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod article_category_usecases;
pub mod article_usecases;
pub mod article_link_usecases;
pub mod article_feedback_usecases;

pub use article_category_usecases::{
    CreateArticleCategoryUseCase, UpdateArticleCategoryUseCase, GetArticleCategoryUseCase,
    DeleteArticleCategoryUseCase, ListArticleCategoryUseCase,
};
pub use article_usecases::{
    CreateArticleUseCase, UpdateArticleUseCase, GetArticleUseCase,
    DeleteArticleUseCase, ListArticleUseCase,
};
pub use article_link_usecases::{
    CreateArticleLinkUseCase, UpdateArticleLinkUseCase, GetArticleLinkUseCase,
    DeleteArticleLinkUseCase, ListArticleLinkUseCase,
};
pub use article_feedback_usecases::{
    CreateArticleFeedbackUseCase, UpdateArticleFeedbackUseCase, GetArticleFeedbackUseCase,
    DeleteArticleFeedbackUseCase, ListArticleFeedbackUseCase,
};

// <<< CUSTOM
// END CUSTOM
