//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod article_category_handler;
pub mod article_handler;
pub mod article_link_handler;
pub mod article_feedback_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use article_category_handler::{create_article_category_routes, create_article_category_read_routes, create_article_category_write_routes};
pub use article_handler::{create_article_routes, create_article_read_routes, create_article_write_routes};
pub use article_link_handler::{create_article_link_routes, create_article_link_read_routes, create_article_link_write_routes};
pub use article_feedback_handler::{create_article_feedback_routes, create_article_feedback_read_routes, create_article_feedback_write_routes};
// <<< CUSTOM
// END CUSTOM
